version: '3'


services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db:/data/db
    restart: always

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/${DB_NAME}
      - PORT=${PORT}

volumes:
  mongo_db: {}