version: '3'


services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_db:/data/db
    restart: always
    profiles:
      - development
      - production

  app-dev:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/${DB_NAME}
      - PORT=${PORT}
    command: npm run dev
    profiles:
      - development

  app-prod:
    build: .
    container_name: app-prod
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/${DB_NAME}
      - PORT=${PORT}
    command: npm start
    profiles:
      - production

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app-prod
    profiles:
      - production
    command: ["nginx", "-g", "daemon off;"]


volumes:
  mongo_db: {}