name: Futtech CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          # Navigate to the deployment directory
            cd /home/ubuntu/financial-instruments/backend || exit 1

          git pull

          docker-compose down
          docker-compose pull
          docker-compose --profile production build
          docker-compose --profile production up -d

          EOF
