name: Futtech CI/CD deployment v1

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Test SSH connection first
          if ! ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH test successful"'; then
            echo "SSH connection failed"
            exit 1
          fi
          
          # Copy files
          scp -i ~/.ssh/deploy_key -r ./* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/project/
          
          # Deploy
          ssh -i ~/.ssh/deploy_key ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/project
            docker-compose down
            docker-compose pull
            docker-compose --profile production up -d
            docker system prune -f
          EOF